/*Format Replace 1/0 to Yes/No*/
PROC FORMAT;
VALUE YesNo
	1 = 'Yes'
	0 = 'No';
RUN;

DATA Sample_data;
	SET ASM.CAR;
	FORMAT 
		VEHICLE_OWNERSHIP YesNo.
		MARRIED YesNo.
		CHILDREN YesNo. 
		OUTCOME YesNo.;
RUN;
/*Clean CREDIT_SCORE*/
PROC SGPLOT DATA = Sample_data;
VBOX CREDIT_SCORE / GROUP = OUTCOME;
RUN;

PROC MEANS DATA = Sample_Data  MIN MAX Q1 MEDIAN Q3 QRANGE;
VAR CREDIT_SCORE;
OUTPUT OUT = STATS Q1 (CREDIT_SCORE) = Q3 (CREDIT_SCORE)= QRANGE (CREDIT_SCORE)= /AUTONAME;
RUN;

/*  ANNUAL_MILEAGE SPEEDING_VIOLATIONS DUIS PAST_ACCIDENTS */
/*  */
DATA OUTLIER;
	SET STATS; 
	LB = CREDIT_SCORE_Q1 - (CREDIT_SCORE_QRANGE*1.5); 
	UB = CREDIT_SCORE_Q3 + (CREDIT_SCORE_QRANGE*1.5);
	
	DROP _TYPE_ _FREQ_;
RUN;

/* DETECT THE OUTLINER VALUES USING THE LB & UB VALUES */
DATA Cleaned_Sample_Data;
	SET Sample_data;
	IF _N_ = 1 THEN SET OUTLIER;
	IF CREDIT_SCORE > UB THEN CREDIT_SCORE = .;
	IF CREDIT_SCORE < LB THEN CREDIT_SCORE = .;
RUN;

PROC STDIZE DATA = Cleaned_Sample_Data REPONLY METHOD=MEAN
	MISSING=MEAN
	OUT=Full_Sample_Data;
	VAR CREDIT_SCORE;
RUN;

PROC SGPLOT DATA = Full_Sample_data;
VBOX CREDIT_SCORE / GROUP = OUTCOME;
RUN;

DATA Sample_Data;
SET Full_Sample_Data;
DROP CREDIT_SCORE_Q1 CREDIT_SCORE_Q3 CREDIT_SCORE_QRANGE LB UB;
RUN;

/*Clean ANNUAL_MILEAGE*/
PROC SGPLOT DATA = Sample_data;
VBOX ANNUAL_MILEAGE / GROUP = OUTCOME;
RUN;

PROC MEANS DATA = Sample_Data  MEAN MIN MAX Q1 MEDIAN Q3 QRANGE;
VAR ANNUAL_MILEAGE;
OUTPUT OUT = STATS Q1 (ANNUAL_MILEAGE) = Q3 (ANNUAL_MILEAGE)= QRANGE (ANNUAL_MILEAGE)= MEAN (ANNUAL_MILEAGE)= /AUTONAME;
RUN;

/*  ANNUAL_MILEAGE SPEEDING_VIOLATIONS DUIS PAST_ACCIDENTS */
DATA OUTLIER;
	SET STATS; 
	LB = ANNUAL_MILEAGE_Q1 - (ANNUAL_MILEAGE_QRANGE*1.5); 
	UB = ANNUAL_MILEAGE_Q3 + (ANNUAL_MILEAGE_QRANGE*1.5);
	
	DROP _TYPE_ _FREQ_;
RUN;


/* DETECT THE OUTLINER VALUES USING THE LB & UB VALUES */
DATA Cleaned_Sample_Data;
	SET Sample_data;
	IF _N_ = 1 THEN SET OUTLIER;

	IF ANNUAL_MILEAGE > UB THEN ANNUAL_MILEAGE = .;
	IF ANNUAL_MILEAGE < LB THEN ANNUAL_MILEAGE = .;
RUN;

PROC STDIZE DATA = Cleaned_Sample_Data REPONLY METHOD=MEAN
	MISSING=MEAN
	OUT=Full_Sample_Data;
	VAR ANNUAL_MILEAGE;
RUN;

PROC SGPLOT DATA = Full_Sample_data;
VBOX ANNUAL_MILEAGE / GROUP = OUTCOME;
RUN;

DATA Sample_Data;
SET Full_Sample_Data;
DROP ANNUAL_MILEAGE_Q1 ANNUAL_MILEAGE_Q3 ANNUAL_MILEAGE_QRANGE LB UB;
RUN;

/************************************************************************/
/* CONTENT OF DATA SET*/
PROC CONTENTS DATA = Sample_data;
RUN;


/* DESCRIPTIVE STATISTICS*/
/*Qualitative*/
/* AGE*/
PROC FREQ DATA = Sample_data;
	TABLES AGE;
	TITLE 'Age';
RUN;

PROC GCHART DATA = Sample_data;
	PIE AGE;
	
	TITLE 'AGE';
RUN;

/*GENDER*/
PROC FREQ DATA = Sample_data;
	TABLES GENDER / PLOTS=FREQPLOT;
	TITLE 'Gender';
RUN;

/*RACE*/
PROC FREQ DATA = Sample_data;
	TABLES RACE / PLOTS=FREQPLOT;
	TITLE 'Race';
RUN;

/*DRIVING_EXPERIENCE*/
PROC FREQ DATA = Sample_data;
	TABLES DRIVING_EXPERIENCE / PLOTS=FREQPLOT;
	TITLE 'DRIVING_EXPERIENCE';
RUN;

/* EDUCATION */
PROC FREQ DATA = Sample_data;
	TABLES EDUCATION;
	TITLE 'EDUCATION_LEVEL';
RUN;

PROC GCHART DATA = Sample_data;
	PIE EDUCATION;
	
	TITLE 'EDUCATION_LEVEL';
RUN;

/* INCOME */
PROC FREQ DATA = Sample_data;
	TABLES INCOME / PLOTS=FREQPLOT;
	TITLE 'INCOME';
RUN;
/* VEHICLE_OWNERSHIP */
PROC FREQ DATA = Sample_data;
	TABLES VEHICLE_OWNERSHIP / PLOTS=FREQPLOT;
	TITLE 'VEHICLE_OWNERSHIP';
RUN;
/* VEHICLE_YEAR */
PROC FREQ DATA = Sample_data;
	TABLES VEHICLE_YEAR / PLOTS=FREQPLOT;
	TITLE 'VEHICLE_YEAR';
RUN;
/* MARRIED */
PROC FREQ DATA = Sample_data;
	TABLES MARRIED;
	TITLE 'MARITAL_STATUS';
RUN;
PROC GCHART DATA = Sample_data;
	PIE MARRIED;
	
	TITLE 'MARITAL_STATUS';
RUN;
/* CHILDREN */
PROC FREQ DATA = Sample_data;
	TABLES CHILDREN / PLOTS=FREQPLOT;
	TITLE 'CHILDREN';
RUN;
/* POSTAL_CODE */
PROC FREQ DATA = Sample_data;
	TABLES POSTAL_CODE / PLOTS=FREQPLOT;
	TITLE 'POSTAL_CODE';
RUN;
/* VEHICLE_TYPE */
PROC FREQ DATA = Sample_data;
	TABLES VEHICLE_TYPE / PLOTS=FREQPLOT;
	TITLE 'VEHICLE_TYPE';
RUN;
/* OUTCOME */
PROC FREQ DATA = Sample_data;
	TABLES OUTCOME / PLOTS= FREQPLOT;
	TITLE 'OUTCOME';
RUN;


/* Quantitative */

/* CREDIT_SCORE*/
PROC MEANS DATA= Sample_data MEAN STDDEV VAR MIN MAX Q1 MEDIAN Q3 QRANGE RANGE SKEWNESS;
	VAR CREDIT_SCORE;
RUN;

PROC UNIVARIATE PLOT DATA= Sample_data;
	VAR CREDIT_SCORE;
	HISTOGRAM;
RUN;

/* ANNUALA_MILEAGE */
PROC MEANS DATA= Sample_data MEAN STDDEV VAR MIN MAX Q1 MEDIAN Q3 QRANGE RANGE SKEWNESS;
	VAR ANNUAL_MILEAGE;
RUN;

PROC UNIVARIATE PLOT DATA= Sample_data;
	VAR ANNUAL_MILEAGE;
	HISTOGRAM;
RUN;

/* SPEEDING_VIOLATIONS */
PROC MEANS DATA= Sample_data MEAN STDDEV VAR MIN MAX Q1 MEDIAN Q3 QRANGE RANGE SKEWNESS;
	VAR SPEEDING_VIOLATIONS;
RUN;

PROC UNIVARIATE PLOT DATA= Sample_data;
	VAR SPEEDING_VIOLATIONS;
	HISTOGRAM;
RUN;

/* DUIS */
PROC MEANS DATA= Sample_data MEAN STDDEV VAR MIN MAX Q1 MEDIAN Q3 QRANGE RANGE SKEWNESS;
	VAR DUIS;
RUN;

PROC UNIVARIATE PLOT DATA= Sample_data;
	VAR DUIS;
	HISTOGRAM;
RUN;

/* PAST_ACCIDENTS */
PROC MEANS DATA= Sample_data MEAN STDDEV VAR MIN MAX Q1 MEDIAN Q3 QRANGE RANGE SKEWNESS;
	VAR PAST_ACCIDENTS;
RUN;

PROC UNIVARIATE PLOT DATA= Sample_data;
	VAR PAST_ACCIDENTS;
	HISTOGRAM;
RUN;

PROC MEANS DATA = Sample_Data NMISS;
run;

/* Relationship*/
/* Driving Experience & Annual Mileage*/
proc sgplot data=Sample_data;
  vbar driving_experience / response=past_accidents stat=mean;
  title "Average Past Accidents by Driving Experience";
  xaxis label="Driving Experience";
  yaxis label="Average Past Accidents";
run;







